
/*fixed parameters used for training*/
#define EXTERNAL_REGRESSOR_NUM 10 
#define INTERNAL_REGRESSOR_NUM 500
#define LAND_MARK_NUM 29
#define FERN_FEATURE_NUM 5
#define TRAIINING_IMAGE_NUM 1345
#define TEST_IMAGE_NUM 507
#define CANDIDATE_PIXEL_NUM 400